export 'package:evaluacion2_jordycontreras/widgets_responsabilidad_social/contenedor_uno_responsabilidad.dart';
export 'package:evaluacion2_jordycontreras/widgets_responsabilidad_social/contenedor_cinco_responsabilidad.dart';
export 'package:evaluacion2_jordycontreras/widgets_responsabilidad_social/contenedor_tres_responsabilidad.dart';
export 'package:evaluacion2_jordycontreras/widgets_responsabilidad_social/contenedor_cuatro_responsabilidad.dart';
export 'package:evaluacion2_jordycontreras/imagenes/Imagen_1_loteria_.dart';
export 'package:evaluacion2_jordycontreras/imagenes/Imagen_2_1er_final_.dart';
export 'package:evaluacion2_jordycontreras/imagenes/Imagen_3_2do_final_.dart';
